### ISSUE TITLE
Chrome Version 40.0.2214.91 breaks text color

### ISSUE THREAD

**Issue by thenimh** [rcalabs/chrome-devtools-flatland-UI#45]
![image](https://cloud.githubusercontent.com/assets/3221476/5889514/45485904-a3e0-11e4-8f7b-e62170144bde.png)

**Comment by zlincoln** [comment]
+1

**Comment by realchaseadams** [comment]
Good catch, that was a _major_ change, I wonder if other themes are having a similar issue. f1e3d360c9612d3f7440822cf351fec73193fc75 fixes this, and has been uploaded to the chrome webstore.

**Comment by akanimh** [comment]
Still seeing the problem on 'Edit as html' 

![image](https://cloud.githubusercontent.com/assets/3221476/6696921/0e976d12-ccaa-11e4-9d8e-7562eb1bcb61.png)
